/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LivroClass;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author T-Gamer
 */
public class TelaVisualizarLivros extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisualizarLivros
     *
     * @throws java.sql.SQLException
     */
    public TelaVisualizarLivros() throws SQLException {
        initComponents();
        LivroClass livroclass_objeto = new LivroClass();
        ResultSet resultset_visualizarlivros = livroclass_objeto.visualizarLivro();
        DefaultTableModel tabela = (DefaultTableModel) jTbResultado.getModel();
        tabela.setNumRows(0);
        while (resultset_visualizarlivros.next()) {
            tabela.addRow(
                    new Object[]{
                        resultset_visualizarlivros.getInt("id_livro"),
                        resultset_visualizarlivros.getString("nome_livro"),
                        resultset_visualizarlivros.getString("autor"),
                        resultset_visualizarlivros.getString("editora"),
                        resultset_visualizarlivros.getString("ano_lancamento"),}
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnPaginaPrincipal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnPaginaPrincipal.setText("PÁGINA PRINCIPAL");
        jBtnPaginaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPaginaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPaginaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1370, -1));

        jTbResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_livro", "nome_livro", "autor", "editora", "ano_lancamento"
            }
        ));
        jScrollPane2.setViewportView(jTbResultado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPaginaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPaginaPrincipalActionPerformed
        // CÓDIGO DO BOTÃO "PÁGINA PRINCIPAL":
        TelaPrincipal telaprincipal_objeto = new TelaPrincipal();
        telaprincipal_objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnPaginaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaVisualizarLivros().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaVisualizarLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPaginaPrincipal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbResultado;
    // End of variables declaration//GEN-END:variables
}
