/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EmprestimoClass;
import javax.swing.JOptionPane;

/**
 *
 * @author T-Gamer
 */
public class TelaCadastrarEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarEmprestimo
     */
    public TelaCadastrarEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnPaginaPrincipal = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jTxtSala = new javax.swing.JTextField();
        jTxtData = new javax.swing.JFormattedTextField();
        jTxtNomeLivro = new javax.swing.JTextField();
        jTxtRm = new javax.swing.JTextField();
        jTxtNomeAluno = new javax.swing.JTextField();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnPaginaPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jBtnPaginaPrincipal.setFont(new java.awt.Font("Artifakt Element", 1, 24)); // NOI18N
        jBtnPaginaPrincipal.setText("PÁGINA PRINCIPAL");
        jBtnPaginaPrincipal.setBorder(null);
        jBtnPaginaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnPaginaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPaginaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPaginaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 1280, 60));

        jBtnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        jBtnCancelar.setFont(new java.awt.Font("Artifakt Element", 1, 24)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancelar.setText("CANCELAR");
        jBtnCancelar.setBorder(null);
        jBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, 460, 90));

        jBtnSalvar.setBackground(new java.awt.Color(0, 153, 51));
        jBtnSalvar.setFont(new java.awt.Font("Artifakt Element", 1, 24)); // NOI18N
        jBtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalvar.setText("SALVAR");
        jBtnSalvar.setBorder(null);
        jBtnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 460, 90));

        jTxtSala.setFont(new java.awt.Font("Artifakt Element", 1, 48)); // NOI18N
        jTxtSala.setText("3° ETIM - Mecatrônica");
        jTxtSala.setBorder(null);
        getContentPane().add(jTxtSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 480, 70));

        jTxtData.setBorder(null);
        try {
            jTxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtData.setText("23/02/2020");
        jTxtData.setFont(new java.awt.Font("Artifakt Element", 1, 48)); // NOI18N
        getContentPane().add(jTxtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 270, 70));

        jTxtNomeLivro.setFont(new java.awt.Font("Artifakt Element", 1, 48)); // NOI18N
        jTxtNomeLivro.setText("As Crônicas de Nárnia");
        jTxtNomeLivro.setBorder(null);
        getContentPane().add(jTxtNomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 1140, 70));

        jTxtRm.setFont(new java.awt.Font("Artifakt Element", 1, 48)); // NOI18N
        jTxtRm.setText("18024");
        jTxtRm.setBorder(null);
        getContentPane().add(jTxtRm, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 330, 70));

        jTxtNomeAluno.setFont(new java.awt.Font("Artifakt Element", 1, 48)); // NOI18N
        jTxtNomeAluno.setText("Marcos Gabriel De Oliveira Favaretto");
        jTxtNomeAluno.setBorder(null);
        getContentPane().add(jTxtNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 660, 70));

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/FundoTelaCadastrarEmprestimo.png"))); // NOI18N
        jFundo.setMaximumSize(new java.awt.Dimension(1366, 768));
        jFundo.setMinimumSize(new java.awt.Dimension(1366, 768));
        jFundo.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1940, 790));

        setSize(new java.awt.Dimension(1367, 787));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limparCampos() {
        jTxtNomeAluno.setText("");
        jTxtRm.setText("");
        jTxtNomeLivro.setText("");
        jTxtData.setText("");
        jTxtSala.setText("");
    }

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // CÓDIGO DO BOTÃO "CANCELAR":
        limparCampos();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPaginaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPaginaPrincipalActionPerformed
        // CÓDIGO DO BOTÃO "PÁGINA PRINCIPAL":
        TelaPrincipal telaprincipal_objeto = new TelaPrincipal();
        telaprincipal_objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnPaginaPrincipalActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // CÓDIGO DO BOTÃO "SALVAR":
        if (!jTxtNomeAluno.getText().equals("") || jTxtRm.getText().equals("") || jTxtNomeLivro.getText().equals("") || jTxtData.getText().equals("") || jTxtSala.getText().equals("")) {
            EmprestimoClass emprestimoclass_objeto = new EmprestimoClass();
            if (emprestimoclass_objeto.cadastrarEmprestimo(jTxtNomeAluno.getText(), jTxtRm.getText(), jTxtNomeLivro.getText(), jTxtData.getText(), jTxtSala.getText())) {
                JOptionPane.showMessageDialog(this, "Empréstimo cadastrado com sucesso!");
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Empréstimo NÃO foi cadastrado, tente novamente!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!");
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnPaginaPrincipal;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jFundo;
    private javax.swing.JFormattedTextField jTxtData;
    private javax.swing.JTextField jTxtNomeAluno;
    private javax.swing.JTextField jTxtNomeLivro;
    private javax.swing.JTextField jTxtRm;
    private javax.swing.JTextField jTxtSala;
    // End of variables declaration//GEN-END:variables
}
